

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
safe: true
lsi: false
markdown: redcarpet
excerpt_separator: "\n\n"
encoding: UTF-8

filter: 'category'

sass:
  style: compressed

######## for 3-Jekyll  end themes

redcarpet:
  extensions: [no_intra_emphasis, fenced_code_blocks, autolink, tables, with_toc_data, highlight, quote]

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

title : 向榫子
author :
  name : 笋子
  email : xiangsunzi@163.com
  github : https://github.com/sun-silence
  weibo : http://weibo.com/p/1005052072316797

