
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "www.xiangsunzi.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

# google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

# force-https: True

#############
# HTML Head #
#############

lang: "cn"
author: "Percy"
title: "{ 梦中的婚礼 }"
description: "婚礼使用的webpage"
keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/love.ico"

background-img: "../img/intro-bg.jpg"
background-img1: "../img/one.jpg"
background-img2: "../img/two.jpg"
background-img3: "../img/three.jpg"
background-img4: "../img/four.jpg"
##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "我们结婚啦！"
  - text: "笋子&振云"


me-img: "/img/jetpacktocat.png"
# <font color="#FF0000">www.divcss5.com 红色</font>

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
weibo-share: True
friend-share: False
qzone-share: True
qq-share: True
disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/marry.jpg"
    date: "2016年1月3日"
    description: "结婚啦"
  - image: "/img/timeline/papre.jpg"
    date: "2015年2月19日"
    description: "订婚"
  - image: "/img/timeline/love.jpg"
    date: "2011年11月24日"
    description: "在一起"
  - image: "/img/timeline/meet.jpg"
    date: "2011年9月17日"
    description: "相遇"

# First image of the Timeline

timeline-img: "/img/timeline/begin.jpg"

###########
# Contact #
###########

email: "xiangsunzi@163.com"

##################
# Social Buttons #
##################

social:
  - title: "空间"
    url: "http://user.qzone.qq.com/1360370242"
    image: "/img/web-app/qzone.ico"
  - title: "微博"
    url: "http://weibo.com/u/2072316797"
    image: "/img/web-app/weibo.ico"
  # - title: "github"
  #   url: "https://github.com/sun-silence"
  #   image: "/img/web-app/github.ico"
############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  我们: 'about'
  博客: 'latest-post'
  时间轴: 'timeline'
  联系我: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate

