#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH

cd _posts
for i in *.txt; do

	filename1=`echo "$i" | awk -F . '{print $1}'`
	filename="$filename1.md"
	rm $filename
	echo "---" >> $filename
	echo "layout: post" >> $filename
	title=`sed -n 1p $i`
	echo "title: $title" >> $filename
	echo "category: 笋子" >>$filename
	echo "---" >>$filename
	sed -i '1d' $i
	echo "" >> $filename
	echo "<center><font color=\"#fff\">" >>$filename
	while read line; do
		echo "$line <br>" >> $filename
	done < $i
	echo "<br>" >> $filename
	echo "</font>
</center>" >> $filename
	rm $i
done

cd -
