#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH
smallfolder=small1
listfile=list1
bigfolder=big1
html=Gallery1


updatehtml(){
	cd $bigfolder
	for m in *.jpg; do
	echo "        <li>" >> ../$listfile
	echo "         	<div class=\"img_block\">" >> ../$listfile
	echo "     		<img src=\"images/$bigfolder/$m\" />" >> ../$listfile
	echo "                  	<a href=\"#\" rel=\"lightbox[plants]\" title=\"测试标题\" class=\"zoom\">放大</a>"  >> ../$listfile
	echo "          	</div>" >> ../$listfile
	echo "            	<h3>TITLE</h3>" >> ../$listfile
	echo "            	<p>简介文字</p>" >> ../$listfile
	echo "        </li>" >> ../$listfile
	done
	cd ../
}

smallfolder=small1
listfile=list1
bigfolder=big1
html=Gallery1
updatehtml
sed -i '/<!-- yunyun -->/r list1' ../$html.html
rm $listfile

smallfolder=small2
listfile=list2
bigfolder=big2
html=Gallery2
updatehtml
sed -i '/<!-- yunyun -->/r list2' ../$html.html
rm $listfile

smallfolder=small3
listfile=list3
bigfolder=big3
html=Gallery3
updatehtml
sed -i '/<!-- yunyun -->/r list3' ../$html.html
rm $listfile

smallfolder=small4
listfile=list4
bigfolder=big4
html=Gallery4
updatehtml
sed -i '/<!-- yunyun -->/r list4' ../$html.html
rm $listfile
